field: b875d1a0-df5b-473e-8045-505e795ed4b7 # Page Builder
fieldLayouts:
  c4d3ac06-62fd-4f58-8a92-2529a3d5b031:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cfbc23c5-b2a7-4f50-9633-6c678949a55c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11463ab7-9a4a-4674-8d2e-7d5240fcb124
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: da5198b6-f659-456d-9260-1dc16bf25ccd # Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bdfe28e-a971-40a9-813e-2a88d5bfe3a2
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: e913f30d-7ff5-4406-99cb-2e4409ee2b33
        userCondition: null
fields:
  cfbc23c5-b2a7-4f50-9633-6c678949a55c: # Text
    columnSuffix: patowylu
    contentColumnType: text
    fieldGroup: null
    handle: headingContent
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  da5198b6-f659-456d-9260-1dc16bf25ccd: # Type
    columnSuffix: hamyezhy
    contentColumnType: string
    fieldGroup: null
    handle: headingType
    instructions: null
    name: Type
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - H1
            -
              - value
              - h1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H4
            -
              - value
              - h4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: heading
name: Heading
sortOrder: 1
