field: b875d1a0-df5b-473e-8045-505e795ed4b7 # Page Builder
fieldLayouts:
  4dd914f8-6cd6-4cd2-8c87-95ca239873d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2bd3bb4-0182-4dfd-a3a0-ae73dd179028 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaf20e63-c4f6-4c63-8c47-11ba7a1f42be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cb8508e2-3617-45e2-84d1-927c5d28fbaf
        userCondition: null
fields:
  e2bd3bb4-0182-4dfd-a3a0-ae73dd179028: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:b1f53ef2-579f-4c8b-8722-b8c8f116cc17' # Featured Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:b1f53ef2-579f-4c8b-8722-b8c8f116cc17' # Featured Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:e517209b-dcc4-469c-b983-d94d2f57b7b3' # Project Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: images
name: Images
sortOrder: 3
