field: b875d1a0-df5b-473e-8045-505e795ed4b7 # Page Builder
fieldLayouts:
  e28da283-9f2b-4f31-8aa0-b327f81d0b0a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 04ff3d9a-055b-413b-8900-1a7006af9a15 # Video Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef22807e-e258-4807-bc38-7745b091381e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc431e59-9e63-47fb-97c8-095af0bdcf3e # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca586b63-de15-4341-b77a-0185f7cfa4e8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8167885f-06ba-4fb8-bcd6-fe963597d2b8
        userCondition: null
fields:
  04ff3d9a-055b-413b-8900-1a7006af9a15: # Video Url
    columnSuffix: dizozfke
    contentColumnType: text
    fieldGroup: null
    handle: videoUrl
    instructions: null
    name: 'Video Url'
    searchable: false
    settings:
      url: ''
    translationKeyFormat: null
    translationMethod: none
    type: wrav\oembed\fields\OembedField
  bc431e59-9e63-47fb-97c8-095af0bdcf3e: # Width
    columnSuffix: udvcsujm
    contentColumnType: string
    fieldGroup: null
    handle: width
    instructions: null
    name: Width
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - medium
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Extra Large'
            -
              - value
              - extraLarge
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: video
name: Video
sortOrder: 4
