baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Cultuur en Vliegwerk'
primary: true
siteGroup: bb0f3428-1448-478f-bf18-2d7e8af0fa9c # Cultuur en Vliegwerk
sortOrder: 1
