columnSuffix: rjvcjlog
contentColumnType: string(560)
fieldGroup: ad571690-fe46-4d3a-bf58-327c58837400 # Common
handle: imageCaption
instructions: null
name: 'Image Caption'
searchable: false
settings:
  byteLimit: null
  charLimit: 140
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
