columnSuffix: null
contentColumnType: string
fieldGroup: ad571690-fe46-4d3a-bf58-327c58837400 # Common
handle: pageBuilder
instructions: null
name: Content
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
