columnSuffix: null
contentColumnType: string
fieldGroup: ad571690-fe46-4d3a-bf58-327c58837400 # Common
handle: projectCategorie
instructions: null
name: 'Project Categorie'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:9ee7d598-ae6f-4601-ae67-e7de75d123f0' # Project Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
