defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  c0f94bf8-c329-41cb-bd14-d6f8199f119c: # Cultuur en Vliegwerk
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
